name: Deploy on push

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Copy files to docker container
      run: docker cp . cc:/app
    - name: Kill the process
      continue-on-error: true
      run: docker exec cc pkill dist
    - name: Download packages
      run: docker exec cc go mod download
    - name: Build the project
      run: docker exec cc go build -o dist -buildvcs=false
    - name: Run the project
      run: docker exec cc ./dist > /dev/null 2>&1 &
